### ISSUE TITLE
Fix `x11-misc/eww/eww-9999.ebuild`

### ISSUE THREAD

**Issue by viandoxdev** [gtoo2/portage-overlay#64]
x11-misc/eww seems to be missing some dependencies: (at least) gtk-layer-shell.
Also, for some reason the `cargo_src_install` fails, because it can't `cargo install` a workspace, and it only works with the old `dobin target/release/"$PN"`, but that may be a problem with my gentoo install or something.

Edit: forgot to ask but, why is the `parallel-compiler` use flag required for dev-lang/rust ? It seems to compile just fine without it

**Comment by m0lese** [comment]
Thank you for taking the time to flag up the problems. I'll look into it and make any required repairs.

**Comment by m0lese** [comment]
@viandoxdev I did the necessary repairs. Thank you for pointing this out. It installs properly now.
![screenshot](https://i.imgur.com/MnpHbLF.png)
